-- HIDROCONTROL PTAP - Tags iniciales

INSERT INTO tags (tag_id, nombre_visible, abreviado, clase, tipo_senal, db_number, address, tipo_dato_s7, unidad, lectura_escritura, historizar, alarma_habilitada, min_value, max_value, descripcion)
VALUES
('bomba_principal_estado', 'Bomba principal estado', 'B1', 'motor', 'digital', 10, 'X0.0', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Estado real B1'),
('dosificador_sulfato_estado', 'Dosificador sulfato estado', 'B2', 'motor', 'digital', 10, 'X0.1', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Estado real B2'),
('dosificador_cloro_estado', 'Dosificador cloro estado', 'B3', 'motor', 'digital', 10, 'X0.2', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Estado real B3'),
('nivel_tanque_agua_cruda', 'Nivel tanque agua cruda', 'S1', 'sensor', 'digital', 10, 'X0.3', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Sensor digital de nivel S1'),
('modo_remoto_habilitado', 'Modo remoto habilitado', NULL, 'seguridad', 'digital', 10, 'X0.4', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Permiso de comandos remotos'),
('plc_en_falla', 'PLC en falla', NULL, 'seguridad', 'digital', 10, 'X0.5', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'Falla general PLC/proceso'),
('comando_rechazado', 'Comando rechazado', NULL, 'seguridad', 'digital', 10, 'X0.6', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'PLC rechazo ultimo comando'),
('ultimo_comando_aceptado', 'Ultimo comando aceptado', NULL, 'seguridad', 'digital', 10, 'X0.7', 'BOOL', NULL, 'lectura', true, true, 0, 1, 'PLC acepto ultimo comando'),
('ph_agua_cruda', 'pH agua cruda', 'S2', 'calidad', 'analogica', 10, 'REAL2', 'REAL', 'pH', 'lectura', true, true, 0, 14, 'S2 escalado en pH'),
('turbidez_agua_cruda', 'Turbidez agua cruda', 'S3', 'calidad', 'analogica', 10, 'REAL6', 'REAL', 'NTU', 'lectura', true, true, 0, 100, 'S3 escalado en NTU'),
('conductividad_agua_cruda', 'Conductividad agua cruda', 'S4', 'calidad', 'analogica', 10, 'REAL10', 'REAL', 'uS/cm', 'lectura', true, true, 0, 2000, 'S4 escalado en uS/cm'),
('ph_agua_tratada', 'pH agua tratada', 'S5', 'calidad', 'analogica', 10, 'REAL14', 'REAL', 'pH', 'lectura', true, true, 0, 14, 'S5 escalado en pH'),
('turbidez_agua_tratada', 'Turbidez agua tratada', 'S6', 'calidad', 'analogica', 10, 'REAL18', 'REAL', 'NTU', 'lectura', true, true, 0, 100, 'S6 escalado en NTU'),
('conductividad_agua_tratada', 'Conductividad agua tratada', 'S7', 'calidad', 'analogica', 10, 'REAL22', 'REAL', 'uS/cm', 'lectura', true, true, 0, 2000, 'S7 escalado en uS/cm'),
('caudal_bomba_principal', 'Caudal bomba principal', 'S8', 'proceso', 'analogica', 10, 'REAL26', 'REAL', 'L/min', 'lectura', true, true, 0, 100, 'S8 escalado en L/min'),
('caudal_distribucion', 'Caudal distribucion', 'S9', 'proceso', 'analogica', 10, 'REAL30', 'REAL', 'L/min', 'lectura', true, true, 0, 100, 'S9 escalado en L/min'),
('presion_bomba_principal', 'Presion bomba principal', 'S10', 'proceso', 'analogica', 10, 'REAL34', 'REAL', 'bar', 'lectura', true, true, 0, 10, 'S10 escalado en bar'),
('watchdog_plc', 'Watchdog PLC', NULL, 'sistema', 'contador', 10, 'DINT38', 'DINT', NULL, 'lectura', false, true, NULL, NULL, 'Contador vivo desde PLC'),
('comando_bomba_principal_start', 'Comando prender bomba principal', 'B1', 'comando', 'digital', 11, 'X0.0', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud prender B1'),
('comando_bomba_principal_stop', 'Comando apagar bomba principal', 'B1', 'comando', 'digital', 11, 'X0.1', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud apagar B1'),
('comando_dosificador_sulfato_start', 'Comando prender dosificador sulfato', 'B2', 'comando', 'digital', 11, 'X0.2', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud prender B2'),
('comando_dosificador_sulfato_stop', 'Comando apagar dosificador sulfato', 'B2', 'comando', 'digital', 11, 'X0.3', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud apagar B2'),
('comando_dosificador_cloro_start', 'Comando prender dosificador cloro', 'B3', 'comando', 'digital', 11, 'X0.4', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud prender B3'),
('comando_dosificador_cloro_stop', 'Comando apagar dosificador cloro', 'B3', 'comando', 'digital', 11, 'X0.5', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud apagar B3'),
('reset_alarmas', 'Reset alarmas', NULL, 'comando', 'digital', 11, 'X0.6', 'BOOL', NULL, 'escritura', true, true, 0, 1, 'Solicitud reset/ack alarmas'),
('watchdog_scada', 'Watchdog SCADA', NULL, 'sistema', 'digital', 11, 'X0.7', 'BOOL', NULL, 'escritura', false, true, 0, 1, 'Pulso vivo Node-RED'),
('command_sequence', 'Secuencia comando', NULL, 'sistema', 'contador', 11, 'DINT2', 'DINT', NULL, 'escritura', true, false, NULL, NULL, 'Consecutivo comando Node-RED')
ON CONFLICT (tag_id) DO UPDATE SET
    nombre_visible = EXCLUDED.nombre_visible,
    abreviado = EXCLUDED.abreviado,
    clase = EXCLUDED.clase,
    tipo_senal = EXCLUDED.tipo_senal,
    db_number = EXCLUDED.db_number,
    address = EXCLUDED.address,
    tipo_dato_s7 = EXCLUDED.tipo_dato_s7,
    unidad = EXCLUDED.unidad,
    lectura_escritura = EXCLUDED.lectura_escritura,
    historizar = EXCLUDED.historizar,
    alarma_habilitada = EXCLUDED.alarma_habilitada,
    min_value = EXCLUDED.min_value,
    max_value = EXCLUDED.max_value,
    descripcion = EXCLUDED.descripcion,
    updated_at = now();
